version: '3.8'
services:
  app-gateway:
    build: ./app-gateway
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - USERS_SERVICE_URL=http://users-service:3006
      - POSTS_SERVICE_URL=http://posts-service:3007
      - DB_SERVICE_URL=http://db:3008
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - users-service
      - posts-service
      - db
      - redis
      - rabbitmq

  users-service:
    build: ./users-service
    ports:
      - "3006:3006"
    environment:
      - PORT=3006
      - DB_SERVICE_URL=http://db:3008
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - db
      - redis
      - rabbitmq

  posts-service:
    build: ./posts-service
    ports:
      - "3007:3007"
    environment:
      - PORT=3007
      - DB_SERVICE_URL=http://db:3008
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - db
      - redis
      - rabbitmq

  db:
    build: ./database
    ports:
      - "3008:3008"
    environment:
      - PORT=3008
      - DATABASE_URL=postgresql://postgres:root123@database:5432/postgres
    depends_on:
      - database

  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db-data:
