version: "3.8"
services:
  app-gateway:
    build: ./app-gateway
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - NODE_ENV=development
      - USERS_SERVICE_URL=http://users-service:3006
      - POSTS_SERVICE_URL=http://posts-service:3007
      - DB=http://db:3008
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      - users-service
      - posts-service
      - db
      - redis
      - rabbitmq

  users-service:
    build: ./users-service
    ports:
      - "3006:3006"
    environment:
      - PORT=3006
      - NODE_ENV=development
      - DB_URL=http://db:3008
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      - db
      - redis
      - rabbitmq

  posts-service:
    build: ./posts-service
    ports:
      - "3007:3007"
    environment:
      - PORT=3007
      - NODE_ENV=development
      - DB_URL=http://db:3008
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      - db
      - redis
      - rabbitmq

  db:
    build: ./database
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=root123
      - POSTGRES_DATABASE=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DATABASE: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data:
